{ pkgs, ... }:
{
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      systemd-boot.configurationLimit = 10;

      # A visible menu IS the rollback mechanism. With timeout = 0 there is no
      # way to select a previous generation without a rescue USB, which makes
      # every risky rebuild unrecoverable. Under Lanzaboote this value still
      # applies: lzbt is handed the loader.conf generated by the systemd-boot
      # module, so `timeout` and `editor` below both flow through to the ESP.
      timeout = 3;

      # The kernel cmdline editor lets anyone at the keyboard append
      # `init=/bin/sh` for a root shell. That is a Secure Boot bypass, and with
      # displayManager autoLogin enabled there is no password gate in front of
      # it either.
      systemd-boot.editor = false;
    };

    # keep boot output quiet and uncluttered (Plymouth splash removed).
    # Drop "quiet" here if you ever want to watch the boot logs to diagnose a slow startup.
    kernelParams = [ "quiet" "loglevel=3" "rd.systemd.show_status=false" "rd.udev.log_level=3" "udev.log_priority=3" ];
    consoleLogLevel = 0;
    initrd.verbose = false;

    kernelPackages = pkgs.linuxPackages_latest;
    # load nintendo controller support on demand, not at boot
    extraModulePackages = [ ];
    kernelModules = [ ];
    supportedFilesystems = [ "ntfs" ];
  };
}
