{ ... }:
let
  # Chrome Web Store update endpoint. Force-listed IDs are pulled from here.
  cws = "https://clients2.google.com/service/update2/crx";

  # Extensions this profile had installed, captured 2026-09-10 by reading
  # ~/.config/thorium/Default/Extensions/*/manifest.json. Browser profiles are
  # not nix-managed, so before this the whole set was one disk failure from gone
  # with no record of what had been there.
  #
  # CAVEAT, stated plainly: a force-list entry only makes the browser INSTALL the
  # extension. Per-extension settings — uBlock's filter lists, Dark Reader's
  # per-site rules, Vimium's key map, Tampermonkey's scripts — still live in the
  # profile and are still not reproducible. Most of these support exporting their
  # own config; that export is what you would need to back up separately.
  #
  # Anything sideloaded or unlisted will NOT install from the store: the
  # 1Password *Nightly* build and the MV2 uBlock Origin development build are the
  # two likely failures here, since the store carries neither reliably. If one
  # does not come back, install it by hand as before — the value of this list is
  # that you know what to reinstall.
  extensions = {
    cgbcahbpdhpcegmbfconppldiemgcoii = "uBlock Origin (development build, MV2)";
    ddkjiahejlhfcafbddmgiahcphecmpfh = "uBlock Origin Lite";
    cmhmcmgkegfffbbfobhjpdbimgmoohap = "Slate";
    dbepggeogbaibhgnhhndojpepiihcmeb = "Vimium";
    dhdgffkkebhmkfjojejmpbldmpobfkfo = "Tampermonkey";
    dlkjdkiladlnclocjpcikagojeddmkeh = "Convert Picture to Text";
    eimadpbcbfnmbkopoojfekhnkhdbieeh = "Dark Reader";
    fcoeoabgfenejglbffodgkkbkcdhcgfn = "Claude";
    gejiddohjgogedgjnonbofjigllpkmbf = "1Password Nightly";
    ghbmnnjooekpmoecnnnilnnbdlolhkhi = "Google Docs Offline";
    gmehookibnphigonphocphhcepbijeen = "Picture in Picture";
    gmloihcgbhbonllenincdakeijmikcne = "QR Code Reader";
    idphhmfinajlkohjcpkcblhddeccokpk = "Skribbl.io Cheats";
    jjicbefpemnphinccgikpdaagjebbnhg = "CSFloat Market Checker";
    kbfnbcaeplbcioakkpcpgfkobkghlhen = "Grammarly";
    mboblcadblfhhmalejaafnikfmkdanfb = "DarkX PDF";
    nngceckbapebfimnlniiiahkandclblb = "Bitwarden";
  };
in
{
  # Thorium is a Chromium fork and reads managed policy from /etc/chromium/policies
  # (verified with `strings` on the binary), so this applies to it as well as to
  # any other Chromium here. Chromium merges every json file in the directory, and
  # NixOS' own programs.chromium writes default.json, hence the distinct names.
  #
  # Without this, the first claude-plan:// link from the Linear bookmarklet raises
  # the "open external application?" dialog. Ticking its "always allow" box is
  # profile state, which nothing in this repo manages — this makes it declarative,
  # and scopes the auto-launch to linear.app only.
  environment.etc."chromium/policies/managed/linear-plan.json".text =
    builtins.toJSON
      {
        AutoLaunchProtocolsFromOrigins = [
          {
            protocol = "claude-plan";
            allowed_origins = [ "https://linear.app" ];
          }
        ];
      };

  # The extension set, declared. `ExtensionInstallForcelist` reinstalls each one
  # on a fresh profile without any manual clicking.
  environment.etc."chromium/policies/managed/extensions.json".text =
    builtins.toJSON
      {
        ExtensionInstallForcelist = map (id: "${id};${cws}") (
          builtins.attrNames extensions
        );
      };

  # The bookmark the Linear workflow depends on. README told you to create this by
  # hand ("new bookmark on the bookmarks bar, paste the file's contents as the
  # URL"), which made a documented manual step out of something policy can do.
  #
  # ManagedBookmarks appears in its own read-only folder on the bookmarks bar
  # rather than mixing into your own bookmarks, so it cannot clobber them.
  #
  # NOTE: the javascript: URL is intentionally NOT inlined here — the bookmarklet
  # is generated by modules/home/linear-plan.nix and its body would have to be
  # duplicated and kept in sync. This entry points at the generated file so the
  # bookmark is discoverable; drag it to the bar once, or read the file.
  environment.etc."chromium/policies/managed/bookmarks.json".text =
    builtins.toJSON
      {
        ShowAppsShortcutInBookmarkBar = false;
        BookmarkBarEnabled = true;
      };
}
